### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by Ram1708** [ahay/src#148]
RSFROOT=/home/ram/RSFSRC PYTHONPATH=/home/ram/RSFSRC/lib/python2.7/site-packages /home/ram/RSFSRC/bin/scons
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
__pycompile(["build/framework/rsf/tex.pyc"], ["build/framework/rsf/tex.py"])
SyntaxError: unqualified exec is not allowed in function 'colorize' it contains a nested function with free variables (tex.py, line 640)

scons: *** Found dependency cycle(s):
  build/user/zone/gendix.h -> build/user/zone/gendix.h

File "/home/ram/RSFSRC/lib/scons-3.0.0/SCons/Taskmaster.py", line 1065, in cleanup
make: *** [all] Error 2

**Comment by Ram1708** [comment]
Thank you
SyntaxError is solved with your suggestions

**Comment by Ram1708** [comment]
> ```
> SyntaxError: unqualified exec is not allowed in function 'colorize' it contains a nested function with free variables (tex.py, line 640)
> ```
> 
> This should be a bug from python
> The problem is caused by this line in tex.py:
> 
> ```
> exec(progs, locals())
> ```
> 
> And it used to be
> 
> ```
> exec progs in locals()
> ```
> 
> This actually is a bug from python. Check the following link.
> https://bugs.python.org/issue21591
> And this problem is fixed in Python 2.7.9. Maybe you can upgrade your python.

Thank you
SyntaxError is solved with your suggestions

**Comment by Ram1708** [comment]
Following  error still persist:

scons: *** Found dependency cycle(s):
build/user/zone/gendix.h -> build/user/zone/gendix.h

File "/home/ram/RSFSRC/lib/scons-3.0.0/SCons/Taskmaster.py", line 1065, in cleanup
make: *** [all] Error 2

**Comment by sripanichy** [comment]
To avoid the dependency cycle, you can simply delete user/zone/gendix.c but
I believe it’s just a warning.

On 27 Jan 2019, at 13:49, Ram <notifications@github.com> wrote:

Following error still persist:

scons: *** Found dependency cycle(s):
build/user/zone/gendix.h -> build/user/zone/gendix.h

File "/home/ram/RSFSRC/lib/scons-3.0.0/SCons/Taskmaster.py", line 1065, in
cleanup
make: *** [all] Error 2

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ahay/src/issues/148#issuecomment-457893577>, or mute
the thread

**Comment by zhichenggeng** [comment]
Fixed in 65693142e5199195db72ffca51738b01bd21f167
